import time
import sys

print("Welcome to my quiz! (mostly about pokémon)")
print(" ")
time.sleep(1.5)
print("There will be 5 questions (not including the age requirement)")
print(" ")
time.sleep(1.2)
print("you are required to answer them in bad grammer, but don't worry about upper and lowercase")
print(" ")
time.sleep(1.7)
print("If you get a question wrong you will have to restart the quiz to carry on.")
print(" ")
time.sleep(1.5)
print("(there is a secret ending aswell)")
print(" ")
time.sleep(1.5)
print("Good luck!")
print(" ")
time.sleep(2)
age_num = int(input("plase enter how old you are:"))
print(" ")
if age_num == 1: 
            print("you're too young. go away")
            sys.exit()
elif age_num == 2:
      print("you're a bit too young to continue")
      sys.exit()
elif age_num == 3:
      print("you're ugly look in the mirror")
      sys.exit()
elif age_num == 4:
      print("congrats you have exited the stage of cying unnecessarily! but you are still too young to continue")
      sys.exit()
elif age_num == 5:
      print("you are a bit young for this. . . just kidding! (not kidding)")
      sys.exit()
elif age_num == 6:
      print("you are getting big! But not old enough to take this quiz sorry!")
      sys.exit()
elif age_num >= 105:
      print("GET OUTTT")
      sys.exit()
else:
      print("okay lets get started")
      print(" ")
      time.sleep(1)
      print("'question 1'")
      print(" ")
      time.sleep(1)
      pokemon = input("do you play Pokémon?").lower()
      print(" ")
      if pokemon == "yes":
            print("okay good to know you had a child hood then!")
            print(" ")
            time.sleep(1.5)
            print("question 2")
            print(" ")
            time.sleep(1)
            fav_pok = input("Whats your favourite pokemon?").lower()
            print(" ")
            if fav_pok == "pikachu":
                  print("go get a life")
                  print(" ")
                  time.sleep(1)
                  carry_on = input("you dont deserve to continue. do you want to carry on?").lower()
                  print(" ")
                  if carry_on == "yes":
                        print("okay lets carry on...")
                        print(" ")
                        time.sleep(3)
                        print("just kidding pikachu lover. Please leave my quiz")
                        time.sleep(10)
                        sys.exit()
            elif fav_pok == "alice oseman":
                  print("you have found the one piece! make sure to pay before you exit")
                  print(" ")
                  time.sleep(2)
                  bargain = int(input("how much will you bargain??"))
                  if bargain <= 5:
                        print("get the heck outta ma property")
                  elif bargain >= 99:
                        print("that is too much")
                        print(" ")
                        time.sleep(1.5)
                        print("this is only one piece of the one piece")
                        print(" ")
                        time.sleep(2)
                        buy = input("do you wish to continue?").lower()
                        print(" ")
                        if buy == "yes":
                              print("ok here is the receipt")
                              print(" ")
                              time.sleep(1.5)
                              print("this is the secret ending")
                              sys.exit()
            elif fav_pok == "charizard":
                  print("i think some one needs to have some originality in their life")
                  print(" ")
                  time.sleep(1)
                  print("question 3")
                  print(" ")
                  time.sleep(1.2)
                  typing_char = input("What is Charizards typing?").lower()
                  print(" ")
                  if typing_char == "fire and flying" or "fire type and flying type" or "fire and flying type":
                        print("correcto!")
                        print(" ")
                        time.sleep(1.5)
                        print("question 4")
                        print(" ")
                        time.sleep(1.2)
                        char_move = input("What is charizards most iconic move?").lower()
                        print(" ")
                        if char_move == "flamethrower":
                              print("correct again!")
                              print(" ")
                              time.sleep(1.5)
                              print("question 5")
                              print(" ")
                              time.sleep(1.2)
                              poke_tcgp1 = input("have you played the Pokémon TCG Pocket?").lower()
                              print(" ")
                              if poke_tcgp1 == "yes":
                                    print("nice! we can friend eachother and play after this quiz which now that i bring it up, im very tired. Goodnight!")
                                    sys.exit()
                              elif poke_tcgp1 == "no":
                                    print("ok thats fine but im very tired so goodnight!")
                                    print(" ")
                                    time.sleep(1.2)
                                    sys.exit()
                              else:
                                    print("now that i bring it up, im very tired. Goodnight!")
                                    sys.exit()
                        else:
                              print("wrongo!")
                              print(" ")
                              time.sleep(1.5)
                              print("quiz over. . .")
                              sys.exit()
                  else:
                        print("wrongo!")
                        print(" ")
                        time.sleep(1.4)
                        print("quiz over . . .")
                        sys.exit()
            elif fav_pok == "blastoise":
                  print("not a bad choice to be fair")
                  print(" ")
                  time.sleep(1.8)
                  print("question 3")
                  print(" ")
                  time.sleep(1.3)
                  typing_blast = input("what is blastoises typing?").lower()
                  print(" ")
                  if typing_blast == "water" or "water type" or "water typing":
                        print("correcto!")
                        print(" ")
                        time.sleep(1.5)
                        print("question 4")
                        print(" ")
                        time.sleep(1.2)
                        blast_move = input("What is blastoises most iconic move?").lower()
                        print(" ")
                        if blast_move == "hydro cannon":
                              print("correct again!")
                              print(" ")
                              time.sleep(1.5)
                              print("question 5")
                              print(" ")
                              poke_tcgp2 = input("Have you played the pokemon TCGP?").lower()
                              print(" ")
                              if poke_tcgp2 == "yes":
                                    print("nice! we can friend eachother and play after this quiz which now that i bring it up, im very tired. Goodnight!")
                                    sys.exit()
                              elif poke_tcgp2 == "no":
                                    print("ok thats fine but im very tired so goodnight!")
                                    sys.exit()
                              else:
                                    print("now that i bring it up, im very tired so goodnight!")
                        else:
                              print("wrongo!")
                              print(" ")
                              time.sleep(1.5)
                              print("quiz over. . .")
                              sys.exit()
                  else:
                        print("wrongo!")
                        print(" ")
                        time.sleep(1.4)
                        print("quiz over. . .")
                        sys.exit()
            elif fav_pok == "venusaur":
                  print("i think your the next president/king/queen")
                  print(" ")
                  time.sleep(1.6)
                  print("question 3")
                  print(" ")
                  time.sleep(1.2)
                  typing_ven = input("what is venasaurs typing?").lower()
                  print(" ")
                  if typing_ven == "grass and poison" or "grass type and poison type" or "grass and poison type":
                        print("correcto!")
                        print(" ")
                        time.sleep(1.5)
                        print("question 4")
                        print(" ")
                        time.sleep(1.2)
                        ven_move = input("what is venasaurs most iconic move?").lower()
                        print(" ")
                        if ven_move == "vine whip":
                              print("correct again!")
                              print(" ")
                              time.sleep(1.5)
                              print("question 5")
                              print(" ")
                              poke_tcgp3 = input("have you played he pokémon TCGP?").lower()
                              print(" ")
                              if poke_tcgp3 == "yes":
                                    print("nice! we can friend eachother and play after this quiz which now that i bring it up, im very tired. Goodnight!")
                                    sys.exit()
                              elif poke_tcgp3 == "no":
                                    print("ok thats fine but im very tired so goodnight!")
                                    sys.exit()
                              else:
                                    print("now that i bring it up, im very tired. Goodnight!")
                                    sys.exit()
                        else:
                              print("wrongo!")
                              print(" ")
                              time.sleep(1.4)
                              print("quiz over. . .")
                              sys.exit()
                  else:
                        print("wrongo!")
                        print(" ")
                        time.sleep(1.4)
                        print("quiz over. . .")
                  sys.exit()
            elif fav_pok == "mewtwo":
                  print("you just like how powerful mewtwo is dont you?")
                  print(" ")
                  time.sleep(1.6)
                  print("question 3")
                  print(" ")
                  time.sleep(1.8)
                  mewt_type = input("whats mewtwo's typing?").lower()
                  print(" ")
                  if mewt_type == "psychic type" or "psychic" or "psychic typing" or  "sykick":
                        print("correcto!")
                        print(" ")
                        time.sleep(1.5)
                        print("question 4")
                        print(" ")
                        time.sleep(1.2)
                        mewt_move = input("what is mewtwos most iconic move?").lower()
                        print(" ")
                        if mewt_move == "psystrike":
                            print("correct again!")
                            print(" ")
                            time.sleep(1.5)
                            print("question 5")
                            print(" ")
                            poke_tcgp4 = input("Have you played the pokemon TCGP?").lower()
                            print(" ")
                            if poke_tcgp4 == "yes":
                                    print("nice! we can friend eachother and play after this quiz which now that i bring it up, im very tired. Goodnight!")
                                    sys.exit()
                            elif poke_tcgp4 == "no":
                                    print("ok thats fine but im very tired so goodnight!")
                                    sys.exit()
                            else:
                                    print("now that i bring it up, im very tired so goodnight!")
                        else:
                            print("wrongo!")
                        print(" ")
                        time.sleep(1.4)
                        print("quiz over. . .")
                        sys.exit()
                  else:
                       print("wrongo!")
                       print(" ")
                       time.sleep(1.4)
                       print("quiz over. . .")
                       sys.exit()
            elif fav_pok == "mew":
                  print("the only reason you like this foating foetus is because you have no friends")
                  print(" ")
                  time.sleep(2)
                  print("question 3")
                  print(" ")
                  time.sleep(1.3)
                  mew_type = input("what is mew's typing?").lower()
                  print(" ")
                  if mew_type == "psychic type" or "psychic" or "psychic typing" or "sykick":
                        print("correcto!")
                        print(" ")
                        time.sleep(1.5)
                        print("question 4")
                        print(" ")
                        mew_move = input("what is mews most iconc move?").lower()
                        print(" ")
                        if mew_move == "psychic":
                            print("correct again!")
                            print(" ")
                            time.sleep(1.5)
                            print("question 5")
                            print(" ")
                            poke_tcgp5 = input("Have you played the pokemon TCGP?").lower()
                            print(" ")
                            if poke_tcgp5 == "yes":
                                print("nice! we can friend eachother and play after this quiz which now that i bring it up, im very tired. Goodnight!")
                                sys.exit()
                            elif poke_tcgp5 == "no":
                                print("ok thats fine but im very tired so goodnight!")
                                sys.exit()
                            else:
                                print("now that i bring it up, im very tired, so goodnight!")
                        else:
                            print("wrongo!")
                            print(" ")
                            time.sleep(1.4)
                            print("quiz over. . .")
                            sys.exit()
                  else:
                        print("wrongo!")
                        print(" ")
                        time.sleep(1.4)
                        print("quiz over. . .")
                        sys.exit()
            elif fav_pok == "articuno":
                  print("you are a very cool person")
                  print(" ")
                  time.sleep(1.5)
                  print("question 3")
                  print(" ")
                  time.sleep(1.2)
                  arti_type = input("what is articunos typing?").lower()
                  if arti_type == "ice and flying" or "ice type and flying type" or "ice and flying type":
                        print("correcto!")
                        print(" ")
                        time.sleep(1.5)
                        print("question 4")
                        print(" ")
                        arti_move = input("what is articunos most iconic move?").lower()
                        print(" ")
                        if arti_move == "freeze dry":
                            print("correct again!")
                            print(" ")
                            time.sleep(1.5)
                            print("question 5")
                            print(" ")
                            poke_tcgp6 = input("Have you played the pokemon TCGP?").lower()
                            print(" ")
                            if poke_tcgp6 == "yes":
                                print("nice! we can friend eachother and play after this quiz which now that i bring it up, im very tired. Goodnight!")
                                sys.exit()
                            elif poke_tcgp6 == "no":
                                 print("ok thats fine but im very tired so goodnight!")
                                 sys.exit()
                            else:
                                 print("ugh im tired of your shenanigans! now that i bring it up, im very tired, so goodnight!")
                                 sys.exit()
                        else:
                            print("wrongo!")
                            print(" ")
                            time.sleep(1.4)
                            print("quiz over. . .")
                            sys.exit()
                  else:
                        print("wrongo!")
                        print(" ")
                        time.sleep(1.2)
                        print("quiz over. . .")
                        sys.exit()
            elif fav_pok == "zapdos":
                  print("you are a very styish person")
                  print(" ")
                  time.sleep(1.5)
                  print("question 3")
                  print(" ")
                  time.sleep(1.2)
                  zap_type = input("what is zapdos typing?").lower()
                  print(" ")
                  if zap_type == "electric and flying" or "electric type and flying type" or "electric and flying type":
                        print("correcto!")
                        print(" ")
                        time.sleep(1.5)
                        print("question 4")
                        print(" ")
                        time.sleep(1.2)
                        zap_move = input("what is zapdos' most iconic move?").lower()
                        print(" ")
                        if zap_move == "thunderstorm":
                            print("correct again!")
                        else:
                            print("wrongo!")
                            print(" ")
                            time.sleep(1.2)
                            print("quiz over. . .")
                            sys.exit()
                  else:
                        print("wrongo!")
                        print(" ")
                        time.sleep(1.2)
                        print("quiz over. . .")
                        sys.exit()
            elif fav_pok == "moltres":
                  print("i would love to be friends with you")
                  print(" ")
                  time.sleep(1.5)
                  print("question 3")
                  print(" ")
                  time.sleep(1.2)
                  molt_type = input("what is moltres typing?").lower()
                  print(" ")
                  if molt_type == "fire and flying" or "fire type and flying type" or "fire and flying type":
                        print("correcto!")
                        print(" ")
                        time.sleep(1.5)
                        print("question 4")
                        print(" ")
                        time.sleep(1.2)
                        molt_move = input("what is moltres' most iconic move?").lower()
                        print(" ")
                        if molt_move == "wildfire":
                            print("correct again!")
                            print(" ")
                            time.sleep(1.5)
                            print("question 5")
                            print(" ")
                            time.sleep(1.2)
                            poke_tcgp7 = input("have you played the  pokemon TCG pocket?").lower()
                            print(" ")
                            if poke_tcgp7 == "yes":
                                print("nice! we can friend eachother and play after this quiz which now that i bring up, im very tired. goodnight!")
                                sys.exit()
                            elif poke_tcgp7 == "no":
                                print("ok thats fine but im very tired so goodnight!")
                                sys.exit()
                            else:
                                print("ugh im tired of your shenanigans! now that i bring it up, im very tired, so goodnight!")
                                sys.exit()
                        else:
                            print("wrongo!")
                        print(" ")
                        time.sleep(1.2)
                        print("quiz over. . .")
                        sys.exit()
                  else:
                        print("wrongo!")
                        print(" ")
                        time.sleep(1.2)
                        print("quiz over. . .")
                        sys.exit()
            elif fav_pok == "eevee":
                  print("will you mary me?")
                  print(" ")
                  time.sleep(1.5)
                  print("question 3")
                  print(" ")
                  time.sleep(1.2)
                  eev_type = input("what is eevee's typing?").lower()
                  print(" ")
                  if eev_type == "normal" or "normal type" or "normal typing":
                        print("correcto!")
                        print(" ")
                        time.sleep(1.5)
                        print("question 4")
                        print(" ")
                        time.sleep(1.2)
                        eev_move = input("what is eevee's signature move?").lower()
                        print(" ")
                        if eev_move == "bouncy bubble" or "buzzy buzz" or "sizzly slide" or "glitzy glow" or "baddy bad" or "sappy seed" or "freezy frost" or "sparkly swirl":
                              print("correct again!")
                              print(" ")
                              time.sleep(1.5)
                              print("question 5")
                              print(" ")
                              time.sleep(1.2)
                              poke_tcgp8 = input("have you played the pokemon TCG pocket?")
                              print(" ")
                              if poke_tcgp8 == "yes":
                                    print("nice! we can friend eachother and play after this quiz which now that i bring up, im very tired. goodnight!")
                                    sys.exit()
                              elif poke_tcgp8 == "no":
                                    print("ok thats fine but im very tired so goodnight!")
                                    sys.exit()
                              else:
                                    print("ugh im tired of your shenanigans! now that i bring it up, im very tired, so goodnight!")
                                    sys.exit()
                        else:
                            print("wrongo!")
                            print(" ")
                            time.sleep(1.2)
                            print("quiz over. . .")
                            sys.exit()
                  else:
                        print("wrongo!")
                        print(" ")
                        time.sleep(1.2)
                        print("quiz over. . .")
                        sys.exit()
            elif fav_pok == "arceus":
                  print("i can easily tell your a power hungry person")
                  print(" ")
                  time.sleep(1.5)
                  print("question 3")
                  print(" ")
                  time.sleep(1.2)
                  arc_type = input("what is arceus' typing?").lower()
                  print(" ")
                  if arc_type == "normal" or "normal type" or "normal typing":
                        print("correcto!")
                        print(" ")
                        time.sleep(1.5)
                        print("question 4")
                        print(" ")
                        time.sleep(1.2)
                        arc_move = input("whats arceus' signature move?").lower()
                        print(" ")
                        if arc_move == "judgement":
                            print("correct again!")
                            print(" ")
                            time.sleep(1.5)
                            print("question 5")
                            print(" ")
                            time.sleep(1.2)
                            poke_tcgp9 = input("have you played the pokemon TCG pocket?").lower()
                            print(" ")
                            if poke_tcgp9 == "yes":
                                print("nice! we can friend eachother and play after this quiz which now that i bring up, im very tired. goodnight!")
                                sys.exit()
                            elif poke_tcgp9 == "no":
                                print("ok thats fine but im very tired so goodnight!")
                                sys.exit()
                            else:
                                print("ugh im tired of your shenanigans! now that i bring it up, im very tired, so goodnight!")                   
                                sys.exit()
                        else:
                            print("wrongo!")
                            print(" ")
                            time.sleep(1.5)
                            print("quiz over. . .")
                  else:
                        print("wrongo!")
                        print(" ")
                        time.sleep(1.2)
                        print("quiz over. . .")
                        sys.exit()
            else:
                  print(f" {fav_pok} isnt bad at all. Good choice!")
                  print(" ")
                  time.sleep(1.5)
                  print("question 3")
                  print(" ")
                  time.sleep(1.2)
                  poke_tcgp = input("have you played the Pokémon TCG Pocket?").lower()
                  print(" ")
                  if poke_tcgp == "yes":
                        print("nice! I cant stop playing it!")
                        print(" ")
                        time.sleep(1.5)
                        print("question 4")
                        print("")
                        poke_TCGP_first_deck = input("what is the first deck that you get for free in pokémon TCGP?").lower()
                        print(" ")
                        if poke_TCGP_first_deck == "sandslash deck" or "sandslash" or "the sandslash deck":
                              print("your on fire!")
                  elif poke_tcgp == "no":
                        print("you should give it a try. its way better than the normal TCG!")
                        print(" ")
                        time.sleep(5)
                        print("question 4")
                        print(" ")
                        time.sleep(1.2)
                        poke_sword_and_shield_starters = input("what is the first 3 pokémon in sword and shield?").lower()
                        print(" ")
                        if poke_sword_and_shield_starters == "sobble and grookey and scorbunny" or "sobble and scorbunny and grookey" or "scorbunny and sobble and grookey" or "scorbunny and grookey and sobble" or "grookey and sobble and scorbunny" or "grookey and scorbunny and sobble":
                              print("your on fire!")
                              print(" ")
                              time.sleep(1.5)
                              print("im actually quite tired, so im sorry but quiz is over")
                              print(" ")
                              print("bye!")
                              sys.exit()
                        else:
                              print("wrongo!")
                              print(" ")
                              time.sleep(1.2)
      else:
            print("okay then nevermind bye")
            print(" ")
            time.sleep(2)
            print("quiz over.  .  .")
            sys.exit()


